server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-management-service
          uri: lb://account-management-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8762/eureka
