server:
  port: 9090

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: account-management-service
          uri: lb://account-management-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**